image: node:18.12.1

definitions: 
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        script:
          - git submodule update --init --recursive
          - npm ci
          - npm run ci:lint
          - npm run coverage
          - npm run build
          - npm run audit
        artifacts:
          - dist/**

pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    master:
      - step: *lint-test-build
      - step:
          name: "publish minor version to npm"
          trigger: manual
          deployment: production
          script:
            - npm version minor -m "Bump version to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.2.0
              variables:
                NPM_TOKEN: $NPM_TOKEN